/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import tallerrestaurante.ControlBD;
import tallerrestaurante.Domiciliario;

/**
 *
 * @author ubuntu
 */
public class inicioRestaurante extends javax.swing.JFrame {

    /**
     * Creates new form inicioRestaurante
     */
    ControlBD control = new ControlBD();
    public inicioRestaurante(ControlBD control) {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelExit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tableProductos = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtNombreProducto = new javax.swing.JTextField();
        jtIdProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtDescripcion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtPrecio = new javax.swing.JTextField();
        btnAgregarProd = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jtTiempoPrep = new javax.swing.JTextField();
        btnCancelarprod = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        labelcc = new javax.swing.JLabel();
        jtccDom = new javax.swing.JTextField();
        labelcc1 = new javax.swing.JLabel();
        labelcc2 = new javax.swing.JLabel();
        labelcc3 = new javax.swing.JLabel();
        labelcc4 = new javax.swing.JLabel();
        labelcc5 = new javax.swing.JLabel();
        jtNomDomi = new javax.swing.JTextField();
        jtApeDomi = new javax.swing.JTextField();
        jtEmailDomi = new javax.swing.JTextField();
        jtTelDomi = new javax.swing.JTextField();
        jtDirDomi = new javax.swing.JTextField();
        btnCancelarDOmi = new javax.swing.JButton();
        btnAgregarDomi = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(250, 147, 1));

        labelExit.setBackground(new java.awt.Color(254, 254, 254));
        labelExit.setFont(new java.awt.Font("Samanata", 1, 24)); // NOI18N
        labelExit.setForeground(new java.awt.Color(254, 254, 254));
        labelExit.setText("X");
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(254, 254, 254));
        jLabel2.setFont(new java.awt.Font("Samanata", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("DOMI-RES'T");

        jLabel3.setBackground(new java.awt.Color(254, 254, 254));
        jLabel3.setFont(new java.awt.Font("Samanata", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("-");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(labelExit)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelExit)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(642, 642, 642))
        );

        jPanel2.setBackground(new java.awt.Color(41, 38, 43));

        tableProductos.setBackground(new java.awt.Color(41, 38, 43));
        tableProductos.setToolTipText("");

        jPanel5.setBackground(new java.awt.Color(41, 38, 43));

        jLabel6.setBackground(new java.awt.Color(254, 254, 254));
        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Id producto:");

        jLabel5.setBackground(new java.awt.Color(254, 254, 254));
        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Nombre:");

        jtNombreProducto.setBackground(new java.awt.Color(183, 183, 183));
        jtNombreProducto.setFont(new java.awt.Font("Samanata", 1, 15)); // NOI18N
        jtNombreProducto.setForeground(new java.awt.Color(1, 1, 1));
        jtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreProductoActionPerformed(evt);
            }
        });
        jtNombreProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNombreProductoKeyTyped(evt);
            }
        });

        jtIdProducto.setBackground(new java.awt.Color(183, 183, 183));
        jtIdProducto.setFont(new java.awt.Font("Samanata", 1, 15)); // NOI18N
        jtIdProducto.setForeground(new java.awt.Color(1, 1, 1));
        jtIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIdProductoActionPerformed(evt);
            }
        });
        jtIdProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtIdProductoKeyTyped(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(254, 254, 254));
        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Descripción:");

        jtDescripcion.setBackground(new java.awt.Color(183, 183, 183));
        jtDescripcion.setFont(new java.awt.Font("Samanata", 1, 15)); // NOI18N
        jtDescripcion.setForeground(new java.awt.Color(1, 1, 1));
        jtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtDescripcionKeyTyped(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(254, 254, 254));
        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Precio:");

        jtPrecio.setBackground(new java.awt.Color(183, 183, 183));
        jtPrecio.setFont(new java.awt.Font("Samanata", 1, 15)); // NOI18N
        jtPrecio.setForeground(new java.awt.Color(1, 1, 1));

        btnAgregarProd.setBackground(new java.awt.Color(253, 189, 100));
        btnAgregarProd.setText("Agregar Producto");
        btnAgregarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarProdMouseClicked(evt);
            }
        });
        btnAgregarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProdActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(254, 254, 254));
        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Tiempo de \npreparación(M):");

        jtTiempoPrep.setBackground(new java.awt.Color(183, 183, 183));
        jtTiempoPrep.setFont(new java.awt.Font("Samanata", 1, 15)); // NOI18N
        jtTiempoPrep.setForeground(new java.awt.Color(1, 1, 1));
        jtTiempoPrep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtTiempoPrepKeyTyped(evt);
            }
        });

        btnCancelarprod.setBackground(new java.awt.Color(255, 82, 82));
        btnCancelarprod.setText("Cancelar");
        btnCancelarprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarprodMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtTiempoPrep, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnCancelarprod, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtTiempoPrep, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarprod, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        tableProductos.addTab("Agregar productos", jPanel5);

        jPanel3.setBackground(new java.awt.Color(41, 38, 43));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        tableProductos.addTab("Productos", jPanel3);

        jPanel4.setBackground(new java.awt.Color(41, 38, 43));

        labelcc.setBackground(new java.awt.Color(254, 254, 254));
        labelcc.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelcc.setForeground(new java.awt.Color(254, 254, 254));
        labelcc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelcc.setText("CC:");

        jtccDom.setBackground(new java.awt.Color(183, 183, 183));
        jtccDom.setFont(new java.awt.Font("Samanata", 1, 15)); // NOI18N
        jtccDom.setForeground(new java.awt.Color(1, 1, 1));
        jtccDom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtccDomActionPerformed(evt);
            }
        });
        jtccDom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtccDomKeyTyped(evt);
            }
        });

        labelcc1.setBackground(new java.awt.Color(254, 254, 254));
        labelcc1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelcc1.setForeground(new java.awt.Color(254, 254, 254));
        labelcc1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelcc1.setText("Apellidos:");

        labelcc2.setBackground(new java.awt.Color(254, 254, 254));
        labelcc2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelcc2.setForeground(new java.awt.Color(254, 254, 254));
        labelcc2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelcc2.setText("Nombres:");

        labelcc3.setBackground(new java.awt.Color(254, 254, 254));
        labelcc3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelcc3.setForeground(new java.awt.Color(254, 254, 254));
        labelcc3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelcc3.setText("Email:");

        labelcc4.setBackground(new java.awt.Color(254, 254, 254));
        labelcc4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelcc4.setForeground(new java.awt.Color(254, 254, 254));
        labelcc4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelcc4.setText("Telefono:");

        labelcc5.setBackground(new java.awt.Color(254, 254, 254));
        labelcc5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelcc5.setForeground(new java.awt.Color(254, 254, 254));
        labelcc5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelcc5.setText("Direccion:");

        jtNomDomi.setBackground(new java.awt.Color(183, 183, 183));
        jtNomDomi.setFont(new java.awt.Font("Samanata", 1, 15)); // NOI18N
        jtNomDomi.setForeground(new java.awt.Color(1, 1, 1));
        jtNomDomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomDomiActionPerformed(evt);
            }
        });
        jtNomDomi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNomDomiKeyTyped(evt);
            }
        });

        jtApeDomi.setBackground(new java.awt.Color(183, 183, 183));
        jtApeDomi.setFont(new java.awt.Font("Samanata", 1, 15)); // NOI18N
        jtApeDomi.setForeground(new java.awt.Color(1, 1, 1));
        jtApeDomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtApeDomiActionPerformed(evt);
            }
        });
        jtApeDomi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtApeDomiKeyTyped(evt);
            }
        });

        jtEmailDomi.setBackground(new java.awt.Color(183, 183, 183));
        jtEmailDomi.setFont(new java.awt.Font("Samanata", 1, 15)); // NOI18N
        jtEmailDomi.setForeground(new java.awt.Color(1, 1, 1));
        jtEmailDomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEmailDomiActionPerformed(evt);
            }
        });
        jtEmailDomi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtEmailDomiKeyTyped(evt);
            }
        });

        jtTelDomi.setBackground(new java.awt.Color(183, 183, 183));
        jtTelDomi.setFont(new java.awt.Font("Samanata", 1, 15)); // NOI18N
        jtTelDomi.setForeground(new java.awt.Color(1, 1, 1));
        jtTelDomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTelDomiActionPerformed(evt);
            }
        });
        jtTelDomi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtTelDomiKeyTyped(evt);
            }
        });

        jtDirDomi.setBackground(new java.awt.Color(183, 183, 183));
        jtDirDomi.setFont(new java.awt.Font("Samanata", 1, 15)); // NOI18N
        jtDirDomi.setForeground(new java.awt.Color(1, 1, 1));
        jtDirDomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDirDomiActionPerformed(evt);
            }
        });
        jtDirDomi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtDirDomiKeyTyped(evt);
            }
        });

        btnCancelarDOmi.setBackground(new java.awt.Color(255, 82, 82));
        btnCancelarDOmi.setText("Cancelar");
        btnCancelarDOmi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarDOmiMouseClicked(evt);
            }
        });

        btnAgregarDomi.setBackground(new java.awt.Color(253, 189, 100));
        btnAgregarDomi.setText("Agregar Domiciliario");
        btnAgregarDomi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarDomiMouseClicked(evt);
            }
        });
        btnAgregarDomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDomiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelcc5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelcc4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelcc3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelcc2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelcc, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelcc1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtccDom, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNomDomi, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtApeDomi, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtEmailDomi, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtTelDomi, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtDirDomi, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnCancelarDOmi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarDomi, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelcc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtccDom, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelcc2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNomDomi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelcc1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtApeDomi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelcc3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEmailDomi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelcc4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtTelDomi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelcc5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtDirDomi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarDOmi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarDomi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        tableProductos.addTab("Agregar Domiciliarios", jPanel4);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        tableProductos.addTab("Domiciliarios", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        tableProductos.addTab("Clientes", jPanel7);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(tableProductos)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(tableProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        tableProductos.getAccessibleContext().setAccessibleName("Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_labelExitMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jtNombreProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNombreProductoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) == false) {
        }else{
            evt.consume();
        }

        if (jtNombreProducto.getText().length()== 50)
        evt.consume();
    }//GEN-LAST:event_jtNombreProductoKeyTyped

    private void jtIdProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtIdProductoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) == false) {
        }else{
            evt.consume();
        }

        if (jtIdProducto.getText().length()== 30)
        evt.consume();
    }//GEN-LAST:event_jtIdProductoKeyTyped

    private void jtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDescripcionKeyTyped

    }//GEN-LAST:event_jtDescripcionKeyTyped

    private void btnAgregarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProdActionPerformed

    private void jtIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIdProductoActionPerformed

    private void btnAgregarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProdMouseClicked
        String id = jtIdProducto.getText();
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese un id para el producto");
            jtIdProducto.setText("");
        }
        String nombre = jtNombreProducto.getText();
        if(nombre.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese un nombre para el producto");
            jtNombreProducto.setText("");
        }
        String descripcion = jtDescripcion.getText();
        if(descripcion.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese una descripción");
            jtDescripcion.setText("");
        }
        Double precio = Double.parseDouble(jtPrecio.getText());
        if(precio <= 0){
            JOptionPane.showMessageDialog(null, "Ingrese un precio para el producto");
            jtPrecio.setText("");
        }
        Integer tiempo = Integer.parseInt(jtTiempoPrep.getText());
        if(tiempo <= 0){
            JOptionPane.showMessageDialog(null, "Ingrese un tiempo de preparación para el producto");
            jtTiempoPrep.setText("");
        }
      
        String respuesta = control.registroProducto(id,nombre,descripcion,precio,tiempo);
        if(respuesta == null){
        JOptionPane.showMessageDialog(null, "Producto registrado");
        }else{
        JOptionPane.showMessageDialog(null, respuesta);
        } 
    }//GEN-LAST:event_btnAgregarProdMouseClicked

    private void jtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreProductoActionPerformed

    private void jtTiempoPrepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTiempoPrepKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) == false) {
            evt.consume();
        }else{

        }

        if (jtTiempoPrep.getText().length()== 11)
        evt.consume();
    }//GEN-LAST:event_jtTiempoPrepKeyTyped

    private void jtccDomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtccDomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtccDomActionPerformed

    private void jtccDomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtccDomKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtccDomKeyTyped

    private void jtNomDomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomDomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomDomiActionPerformed

    private void jtNomDomiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomDomiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomDomiKeyTyped

    private void jtApeDomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtApeDomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtApeDomiActionPerformed

    private void jtApeDomiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtApeDomiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtApeDomiKeyTyped

    private void jtEmailDomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEmailDomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEmailDomiActionPerformed

    private void jtEmailDomiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEmailDomiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEmailDomiKeyTyped

    private void jtTelDomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTelDomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTelDomiActionPerformed

    private void jtTelDomiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTelDomiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTelDomiKeyTyped

    private void jtDirDomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDirDomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDirDomiActionPerformed

    private void jtDirDomiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDirDomiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDirDomiKeyTyped

    private void btnCancelarDOmiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarDOmiMouseClicked
        // TODO add your handling code here:
        jtNomDomi.setText("");
        jtApeDomi.setText("");
        jtEmailDomi.setText("");
        jtTelDomi.setText("");
        jtDirDomi.setText("");
        jtccDom.setText("");
        
    }//GEN-LAST:event_btnCancelarDOmiMouseClicked

    private void btnAgregarDomiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarDomiMouseClicked
        String nombre = jtNomDomi.getText();
        if(nombre.isEmpty()){
            JOptionPane.showMessageDialog(null,"El nombre esta vacio");
        }
        String apellidos = jtApeDomi.getText();
        if(apellidos.isEmpty()){
            JOptionPane.showMessageDialog(null,"El apellido esta vacio");
        }
        String email = jtEmailDomi.getText();
        if(email.isEmpty()){
            JOptionPane.showMessageDialog(null,"El email esta vacio");
        }
        String telefono = jtTelDomi.getText();
        if(telefono.isEmpty()){
            JOptionPane.showMessageDialog(null,"El telefono esta vacio");
        }
        String direccion = jtDirDomi.getText();
        if(direccion.isEmpty()){
            JOptionPane.showMessageDialog(null,"La direccion esta vacia");
        }
        String cc = jtccDom.getText();
        if(cc.isEmpty()){
            JOptionPane.showMessageDialog(null,"La cc esta vacia");
        }
        
        String respuesta = control.registroDomiciliario(cc,nombre,apellidos,email,telefono,direccion);
        if(respuesta == null){
        JOptionPane.showMessageDialog(null, "Domiciliario registrado");
        }else{
        JOptionPane.showMessageDialog(null, respuesta);
        } 
    }//GEN-LAST:event_btnAgregarDomiMouseClicked

    private void btnAgregarDomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDomiActionPerformed
        
    }//GEN-LAST:event_btnAgregarDomiActionPerformed

    private void btnCancelarprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarprodMouseClicked
        // TODO add your handling code here:
        jtIdProducto.setText("");
        jtNombreProducto.setText("");
        jtPrecio.setText("");
        jtDescripcion.setText("");
        jtTiempoPrep.setText("");
    }//GEN-LAST:event_btnCancelarprodMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarDomi;
    private javax.swing.JButton btnAgregarProd;
    private javax.swing.JButton btnCancelarDOmi;
    private javax.swing.JButton btnCancelarprod;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jtApeDomi;
    private javax.swing.JTextField jtDescripcion;
    private javax.swing.JTextField jtDirDomi;
    private javax.swing.JTextField jtEmailDomi;
    private javax.swing.JTextField jtIdProducto;
    private javax.swing.JTextField jtNomDomi;
    private javax.swing.JTextField jtNombreProducto;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTextField jtTelDomi;
    private javax.swing.JTextField jtTiempoPrep;
    private javax.swing.JTextField jtccDom;
    private javax.swing.JLabel labelExit;
    private javax.swing.JLabel labelcc;
    private javax.swing.JLabel labelcc1;
    private javax.swing.JLabel labelcc2;
    private javax.swing.JLabel labelcc3;
    private javax.swing.JLabel labelcc4;
    private javax.swing.JLabel labelcc5;
    private javax.swing.JTabbedPane tableProductos;
    // End of variables declaration//GEN-END:variables
}
